### ISSUE TITLE
Error with python 2.7.10

### ISSUE THREAD

**Issue by cotuex** [robrua/cassiopeia#18]
Hello, I downloaded your library but when I imported it, it says:

>Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from cassiopeia import riotapi
  File "C:\Python27\lib\site-packages\cassiopeia\riotapi.py", line 5, in <module>
    import cassiopeia.dto.requests
  File "C:\Python27\lib\site-packages\cassiopeia\dto\requests.py", line 5, in <module>
    import urllib.parse
ImportError: No module named parse

You should use the [Request](http://www.python-requests.org/en/latest/) library for that reason. I'm using python 2.7.10.

**Comment by robrua** [comment]
Hey - Cassiopeia is currently a Python 3 library. See #17.
