### ISSUE TITLE
No module name parse

### ISSUE THREAD

**Issue by i32ropie** [robrua/cassiopeia#3]
```python
>>> from cassiopeia import riotapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cassiopeia/riotapi.py", line 5, in <module>
    import cassiopeia.dto.requests
  File "/usr/local/lib/python2.7/dist-packages/cassiopeia/dto/requests.py", line 5, in <module>
    import urllib.parse
ImportError: No module named parse
```

And I have done this before:

```bash
pi@raspberry ~/rito $ sudo pip install parse
Collecting parse
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading parse-1.6.6-py2-none-any.whl
Installing collected packages: parse
Successfully installed parse-1.6.6
```

Any idea?

**Comment by jjmaldonis** [comment]
Cassiopeia only supports Python 3+ (actually we only have tested it on 3.4 so far). That parse error is due to changes from 2 to 3.

**Comment by i32ropie** [comment]
oh :( ok ><
