### ISSUE TITLE
Help with sqlalchemy error

### ISSUE THREAD

**Issue by dantedog** [robrua/cassiopeia#52]
Gonna start by saying I'm definitely a bit over my head here and I'm having a hard time trying to figure out what's going wrong. It's probably a mistake in my environment or something silly.

When I try to get cassiopeia to store its cache in a db, I get an error from sqlalchemy saying
`sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'cassiopeia.type.dto.summoner.Summoner'>` 

Any suggestions on how to poke around with this?

```
from cassiopeia import riotapi
from cassiopeia.type.api import store

import apikey

REGION = 'NA'
API_KEY = apikey.API_KEY
riotapi.set_region(REGION)
riotapi.set_api_key(API_KEY)
store.__sa_bound = True
my_store = store.SQLAlchemyDB(flavor="mysql+pymysql", host="localhost", database="lol", username="cassio",
                              password="password")
riotapi.set_data_store(my_store)



summoner = riotapi.get_summoner_by_name("FatalElement")
print("{name} is a level {level} summoner on the NA server.".format(name=summoner.name, level=summoner.level))

```

````
/home/devin/.virtualenvs/lol/bin/python /home/devin/PycharmProjects/lol/store_test.py
Traceback (most recent call last):
  File "/home/devin/PycharmProjects/lol/store_test.py", line 19, in <module>
    summoner = riotapi.get_summoner_by_name("FatalElement")
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/cassiopeia/core/summonerapi.py", line 95, in get_summoner_by_name
    summoner = cassiopeia.core.requests.data_store.get(cassiopeia.type.core.summoner.Summoner, name, "name")
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/cassiopeia/type/api/store.py", line 229, in get
    val = self.session.query(class_.dto_type).filter(getattr(class_.dto_type, key_field) == keys).first()
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 1272, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 110, in __init__
    self._set_entities(entities)
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 118, in _set_entities
    entity_wrapper(self, ent)
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 3804, in __init__
    "expected - got '%r'" % (column, )
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'cassiopeia.type.dto.summoner.Summoner'>'

Process finished with exit code 1
```

Python 3.4.3

**Comment by robrua** [comment]
Based on this code block `store.__sa_bound = True` is almost certainly your problem. The sqlalchemy bindings aren't getting set up properly because you're essentially telling it that's already been done when it hasn't yet.

In general in Python you should treat attributes that begin with underscores as "for internal use", and never access them from outside the defining class/module without knowing exactly how they work. You can read more about this in [PEP 8](https://www.python.org/dev/peps/pep-0008/)

**Comment by dantedog** [comment]
Ah, right. I had tried toggling that in order to get around 

```
/home/devin/.virtualenvs/lol/bin/python /home/devin/PycharmProjects/lol/store_test.py
Traceback (most recent call last):
  File "/home/devin/PycharmProjects/lol/store_test.py", line 12, in <module>
    password="password")
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/cassiopeia/type/api/store.py", line 211, in __init__
    _sa_bind_typesystem()
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/cassiopeia/type/api/store.py", line 301, in _sa_bind_typesystem
    cassiopeia.type.dto.championmastery._sa_bind_all()
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/cassiopeia/type/dto/championmastery.py", line 56, in _sa_bind_all
    _sa_bind_champion_mastery()
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/cassiopeia/type/dto/championmastery.py", line 42, in _sa_bind_champion_mastery
    class ChampionMastery(ChampionMastery, cassiopeia.type.dto.common.BaseDB):
  File "/home/devin/.virtualenvs/lol/lib/python3.4/site-packages/cassiopeia/type/dto/championmastery.py", line 52, in ChampionMastery
    playerId = sqlalchemy.Column(sqlalchemy.sqlalchemy.Integer, primary_key=True)
AttributeError: 'module' object has no attribute 'sqlalchemy'

Process finished with exit code 1

```

Is there something specific required to have it import sqlalchemy?

**Comment by robrua** [comment]
Ah, you have a version of the code w/a typo in it (the `sqlalchemy.sqlalchemy.Integer`). This has been fixed and if you pull the latest version off this repo it should work. The change will also be in the next release.

**Comment by dantedog** [comment]
Thank you so much. One problem down, a lot of learning to go :) 

I really appreciate the quick response.
